name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Debug JAR_NAME
        run: echo "JAR_NAME=${{ env.JAR_NAME }}"


      - name: Get JAR file name
        id: jar-name
        run: |
          JAR_NAME=$(ls build/libs/*.jar)
          echo "JAR_NAME=${JAR_NAME}" >> $GITHUB_ENV

      - name: Debug JAR_NAME2
        run: echo "JAR_NAME=${{ env.JAR_NAME }}"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build --build-arg JAR_FILE=${{ env.JAR_NAME }} -t your-dockerhub-username/your-app-name:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/your-app-name:${{ github.sha }}

      - name: Logout from Docker Hub
        run: docker logout
