name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Debug JAR_NAME
        run: echo "JAR_NAME=${{ env.JAR_NAME }}"


      - name: Get JAR file name
        id: jar-name
        run: |
            JAR_NAME=$(find ./build/libs -name 'demo-0.0.1-SNAPSHOT.jar' | head -n 1)
            echo "JAR_NAME=${JAR_NAME}" >> $GITHUB_ENV
            echo "Debug JAR_NAME: ${JAR_NAME}"  # Debugging output

      - name: Debug JAR_NAME2
        run: echo "JAR_NAME=${{ env.JAR_NAME }}"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build --build-arg JAR_FILE=${{ env.JAR_NAME }} -t ${{ secrets.DOCKER_USERNAME }}/pddungeongame:${{ github.sha }}
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/pddungeongame:${{ github.sha }}

      - name: Logout from Docker Hub
        run: docker logout
#test